# tests/test_session_reporter.py
"""Smoke tests for session_reporter: report generation with mocked LLM."""
import sys
import json
import time
sys.path.insert(0, 'src')

import pytest
from unittest.mock import patch, MagicMock
from pathlib import Path


SESSION = {
    'session_id': 'test-sess-001',
    'event': 'end',
    'start_ts': time.time() - 1800,
    'duration_seconds': 1800,
    'distance_km': 25.3,
    'max_coolant': 96,
    'min_voltage': 14.1,
}

LLM_NARRATIVE = "Great drive! Coolant stayed stable at 96°C.\n\n- Check oil level\n- Monitor STFT\n- Inspect wiper blades"


def test_build_report_calls_llm_and_returns_markdown(tmp_path):
    import session_reporter as sr
    mock_result = {
        'text': LLM_NARRATIVE,
        'model': 'ollama/qwen2.5:3b',
        'backend': 'ollama',
        'tokens': 80,
        'cached': False,
    }
    with patch('session_reporter.llm_client.query', return_value=mock_result), \
         patch.object(sr, 'REPORTS_DIR', tmp_path):
        report = sr._build_report(SESSION)

    assert isinstance(report, dict)
    assert 'markdown' in report
    assert 'narrative' in report
    assert 'session_id' in report
    assert report['session_id'] == 'test-sess-001'
    assert LLM_NARRATIVE.strip() in report['narrative']
    assert '# Drive Report' in report['markdown']
    assert 'test-sess-001' in report['markdown']


def test_persist_writes_md_and_json(tmp_path):
    import session_reporter as sr
    mock_result = {'text': LLM_NARRATIVE, 'model': 'ollama/x', 'backend': 'ollama', 'tokens': 50, 'cached': False}
    with patch('session_reporter.llm_client.query', return_value=mock_result), \
         patch.object(sr, 'REPORTS_DIR', tmp_path):
        report = sr._build_report(SESSION)
        path = sr._persist(report)

    assert path is not None
    assert path.exists()
    assert path.suffix == '.md'
    json_path = path.with_suffix('.json')
    assert json_path.exists()
    data = json.loads(json_path.read_text())
    assert data['session_id'] == 'test-sess-001'


def test_build_report_fallback_when_llm_fails(tmp_path):
    import session_reporter as sr
    with patch('session_reporter.llm_client.query', side_effect=RuntimeError("LLM offline")), \
         patch.object(sr, 'REPORTS_DIR', tmp_path):
        report = sr._build_report(SESSION)

    assert 'LLM cascade offline' in report['narrative']
    assert report['backend'] == 'static'


def test_summary_packet_contains_vehicle_info():
    import session_reporter as sr
    from config import VEHICLE, VEHICLE_YEAR
    packet = sr._summary_packet(SESSION)
    assert str(VEHICLE_YEAR) in packet
    assert VEHICLE in packet or 'VEHICLE' in packet


def test_render_markdown_has_required_sections():
    import session_reporter as sr
    md = sr._render_markdown(SESSION, LLM_NARRATIVE)
    assert '# Drive Report' in md
    assert 'test-sess-001' in md
    assert LLM_NARRATIVE.strip() in md
    assert 'Generated by DRIFTER' in md
