# MZ1312 DRIFTER — NanoMQ Configuration

listeners.tcp {
    bind = "0.0.0.0:1883"
}

log {
    to = [file]
    level = warn
    dir = "/var/log/nanomq"
    file = "nanomq.log"
    rotation {
        size = 10MB
        count = 3
    }
}
