#!/usr/bin/env python3
"""
MZ1312 DRIFTER — Session Reporter (Tier 3)
End-of-drive narrative reporter. Combines the existing session_analyst data
(SQLite) with v2 telemetry windows, trip stats, safety events, and KB notes
to produce a human-readable report (markdown + JSON). Distinct from
session_analyst.py which targets diagnostic JSON for tooling — this one
targets the driver and posts a summary the dashboard can read.
UNCAGED TECHNOLOGY — EST 1991
"""

import json
import logging
import signal
import threading
import time
from datetime import datetime
from pathlib import Path
from typing import List, Optional

import paho.mqtt.client as mqtt

import llm_client_v2
from config import (
    MQTT_HOST, MQTT_PORT, TOPICS,
    REPORTS_DIR, VEHICLE, VEHICLE_YEAR,
)

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [REPORTER] %(message)s',
    datefmt='%H:%M:%S'
)
log = logging.getLogger(__name__)

# Rolling per-session collectors
_safety_events: List[dict] = []
_trip_events: List[dict] = []
_diagnoses: List[dict] = []
_telemetry_windows: List[dict] = []
_last_trip: dict = {}
_last_session: dict = {}
_lock = threading.Lock()

REPORT_SYSTEM = (
    "You write friendly, accurate post-drive reports for a vehicle owner. "
    "Markdown only. 4–8 sentences total, plus a 3–6 bullet list of action items. "
    "Reference real numbers from the data. No marketing fluff."
)


def _summary_packet(session: dict) -> str:
    parts = [
        f"VEHICLE: {VEHICLE_YEAR} {VEHICLE}",
        f"SESSION: {session.get('session_id', 'unknown')}",
        f"  Duration: {int(session.get('duration_seconds', 0) // 60)} min",
        f"  Distance: {session.get('distance_km', 0):.1f} km",
        f"  Max coolant: {session.get('max_coolant', '?')}°C",
        f"  Min voltage: {session.get('min_voltage', '?')}V",
    ]
    if _last_trip:
        parts.append(
            f"  Fuel used: {_last_trip.get('fuel_l', '?')} L "
            f"({_last_trip.get('avg_l_per_100km', '?')} L/100km, "
            f"£{_last_trip.get('cost_gbp', '?')})"
        )
    if _safety_events:
        parts.append("")
        parts.append(f"SAFETY EVENTS ({len(_safety_events)}):")
        for ev in _safety_events[-8:]:
            parts.append(f"  - [{ev.get('name')}] {ev.get('message', '')[:200]}")
    if _diagnoses:
        parts.append("")
        parts.append(f"AI DIAGNOSES ({len(_diagnoses)}):")
        for d in _diagnoses[-3:]:
            diag = d.get('diagnosis') or {}
            primary = diag.get('primary_suspect') or {}
            if primary:
                parts.append(
                    f"  - {primary.get('diagnosis', '?')} "
                    f"({primary.get('confidence', '?')}%)"
                )
    return '\n'.join(parts)


def _render_markdown(session: dict, narrative: str) -> str:
    sid = session.get('session_id', 'unknown')
    start = datetime.fromtimestamp(session.get('start_ts', time.time()))
    return (
        f"# Drive Report — {sid}\n"
        f"_{start:%Y-%m-%d %H:%M}_\n\n"
        f"{narrative.strip()}\n\n"
        f"---\n"
        f"_Generated by DRIFTER session reporter._\n"
    )


def _build_report(session: dict) -> dict:
    packet = _summary_packet(session)
    narrative = ""
    backend = "static"
    try:
        result = llm_client_v2.query(packet, REPORT_SYSTEM, max_tokens=600, cache=False)
        narrative = result.get('text', '').strip()
        backend = result.get('backend', 'llm')
    except Exception as e:
        log.warning(f"Narrative generation failed: {e}")
        narrative = "Drive complete. LLM cascade offline — stats only:\n\n" + packet

    markdown = _render_markdown(session, narrative)
    report = {
        'session_id': session.get('session_id'),
        'ts': time.time(),
        'narrative': narrative,
        'markdown': markdown,
        'metrics': {
            'duration_seconds': session.get('duration_seconds'),
            'distance_km': session.get('distance_km'),
            'max_coolant': session.get('max_coolant'),
            'min_voltage': session.get('min_voltage'),
        },
        'safety_event_count': len(_safety_events),
        'diagnosis_count': len(_diagnoses),
        'trip': _last_trip,
        'backend': backend,
    }
    return report


def _persist(report: dict) -> Optional[Path]:
    try:
        REPORTS_DIR.mkdir(parents=True, exist_ok=True)
        out = REPORTS_DIR / f"summary_{report.get('session_id', 'unknown')}.md"
        out.write_text(report.get('markdown', ''))
        json_out = REPORTS_DIR / f"summary_{report.get('session_id', 'unknown')}.json"
        json_out.write_text(json.dumps(report, indent=2))
        return out
    except Exception as e:
        log.warning(f"Persist failed: {e}")
        return None


def _handle_session_end(client: mqtt.Client, session: dict) -> None:
    log.info(f"Building report for session {session.get('session_id')}")
    report = _build_report(session)
    _persist(report)
    client.publish(TOPICS['session_report'], json.dumps(report), retain=True)
    client.publish(TOPICS['session_summary'], json.dumps({
        'session_id': report['session_id'],
        'narrative': report['narrative'],
        'ts': report['ts'],
    }))
    # Reset per-session collectors
    with _lock:
        _safety_events.clear()
        _diagnoses.clear()
        _trip_events.clear()
        _telemetry_windows.clear()


def on_message(client, userdata, msg) -> None:
    global _last_trip, _last_session
    topic = msg.topic
    try:
        data = json.loads(msg.payload)
    except (json.JSONDecodeError, UnicodeDecodeError):
        return

    if topic == TOPICS['safety_alert'] and isinstance(data, dict):
        with _lock:
            _safety_events.append(data)
    elif topic == TOPICS['ai_diag_response'] and isinstance(data, dict):
        with _lock:
            _diagnoses.append(data)
    elif topic == TOPICS['trip_stats'] and isinstance(data, dict):
        _last_trip = data
    elif topic == TOPICS['telemetry_window'] and isinstance(data, dict):
        with _lock:
            _telemetry_windows.append(data)
            if len(_telemetry_windows) > 600:
                _telemetry_windows.pop(0)
    elif topic == TOPICS['drive_session'] and isinstance(data, dict):
        if data.get('event') == 'end':
            _last_session = data
            threading.Thread(
                target=_handle_session_end, args=(client, data), daemon=True,
            ).start()
        elif data.get('event') == 'start':
            _last_session = data


def main() -> None:
    log.info("DRIFTER Session Reporter starting...")

    running = True

    def _handle_signal(sig, frame):
        nonlocal running
        running = False

    signal.signal(signal.SIGTERM, _handle_signal)
    signal.signal(signal.SIGINT, _handle_signal)

    client = mqtt.Client(client_id="drifter-reporter")
    client.on_message = on_message

    connected = False
    while not connected and running:
        try:
            client.connect(MQTT_HOST, MQTT_PORT, 60)
            connected = True
        except Exception as e:
            log.warning(f"Waiting for MQTT broker... ({e})")
            time.sleep(3)

    if not running:
        return

    client.subscribe([
        (TOPICS['drive_session'], 0),
        (TOPICS['safety_alert'], 0),
        (TOPICS['ai_diag_response'], 0),
        (TOPICS['trip_stats'], 0),
        (TOPICS['telemetry_window'], 0),
    ])
    client.loop_start()
    log.info("Session Reporter LIVE")

    while running:
        time.sleep(1)

    client.loop_stop()
    client.disconnect()
    log.info("Session Reporter stopped")


if __name__ == '__main__':
    main()
